# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  influx:
    url: http://192.168.23.5:8086
    user: beibei
    password: Aa123456
  mail:
    host: smtp.163.com
    username: 17784774733@163.com
    password: CXFLNTXKRTWXQNRP
  rabbitmq:
    addresses: 192.168.23.5:5673
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 10000
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  data:
    redis:
      host: 192.168.23.5
      port: 6379
  monitor:
    current-client-ip: 10.61.80.160