version: '3'
services:
  backend:
    image: beibei-monitor-backend:v1
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
      - redis
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://154.3.1.23:3306/monitor
      - SPRING_INFLUX_URL=http://influxdb:8086
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_DATA_REDIS_HOST=redis

  frontend:
    image: beibei-monitor-frontend:v1
    ports:
      - "80:80"

  influxdb:
    image: influxdb:2.7.4
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=beibei
      - DOCKER_INFLUXDB_INIT_PASSWORD=Aa123456
      - DOCKER_INFLUXDB_INIT_ORG=beibei
      - DOCKER_INFLUXDB_INIT_BUCKET=beibei
    volumes:
      - influxdb-data:/var/lib/influxdb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306                             #将外部端口33307映射为内部默认创建的3306
    volumes:
      - ./mysql/data/mysql:/var/lib/mysql            #将容器中运行的mysql数据保存到宿主机，防止容器删除后数据丢失
      - ./mysql/init:/docker-entrypoint-initdb.d/    #/docker-entrypoint-initdb.d/这是数据库提供的初始化目录，数据库在启动时会默认执行当期目录下的以.sql或者.sh结尾的文件。
    environment:
      MYSQL_ROOT_PASSWORD: 123456                #数据库初始话为root用户设置的默认密码
      MYSQL_DATABASE: monitor                 #数据库名
    restart: on-failure                          #重启条件

volumes:
  influxdb-data: