version: '3'
services:
  backend:
    container_name: beibei_monitor_backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
      - redis
      - rabbitmq
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/monitor
      - SPRING_INFLUX_URL=http://influxdb:8086
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_DATA_REDIS_HOST=redis

  frontend:
    container_name: beibei_monitor_frontend
    build: ./nginx
    ports:
      - "80:80"

  influxdb:
    container_name: monitor_influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=beibei
      - DOCKER_INFLUXDB_INIT_PASSWORD=Aa123456
      - DOCKER_INFLUXDB_INIT_ORG=beibei
      - DOCKER_INFLUXDB_INIT_BUCKET=beibei
    volumes:
      - influxdb-data:/var/lib/influxdb

  redis:
    container_name: monitor_redis
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: monitor_rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  mysql:
    container_name: monitor_mysql
    build: ./mysql
    ports:
      - "3306:3306"                             #将外部端口33307映射为内部默认创建的3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123456                #数据库初始话为root用户设置的默认密码
      MYSQL_DATABASE: monitor                 #数据库名
    restart: on-failure                          #重启条件

volumes:
  influxdb-data:
